In [1]:
import tensorflow as tf 

print("=== Tensor Creation ===")
scalar = tf.constant(10)
vector = tf.constant([1,2,3,4])
matrix = tf.constant([[1,2],[3,4]])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)

# Create tensors with specific data type
tensor_float = tf.constant([1.0,2.0,3.0] , dtype= tf.float32)
print("Float Tensor:",tensor_float)

# Random and zero tensors
rand_tensor = tf.random.normal([2,2])
zeros_tensor = tf.zeros([3,3])
ones_tensor = tf.ones([2,3])

print("Random Tensor:\n", rand_tensor)
print("Zeros Tensor:\n", zeros_tensor)
print("Ones Tensor:\n", ones_tensor)

print("\n=== Tensor Manipulation ===")

# reshaped tensor 
reshaped = tf.reshape(tf.range(9),(3,3))
print("Reshaped Tensor:\n" , reshaped)

# Slicing and indexing
print("First Row:" , reshaped[0])
print("Element [1,2]:" , reshaped[1,2])

# Concatenation
tensor1 = tf.constant([[1,2]])
tensor2 = tf.constant([[3,4]])
concat_tensor = tf.concat([tensor1 , tensor2] , axis=0)
print("Concatenated Tensor:\n", concat_tensor)

# Arithmetic operations
a = tf.constant([2, 4, 6])
b = tf.constant([1, 3, 5])
print("Addition:", tf.add(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Matrix Multiplication:\n", tf.matmul([[1, 2]], [[3], [4]]))

print("\n=== Computation Graphs using @tf.function ===")

@tf.function
def compute_graph(x,y) : 
    z = tf.multiply(x , y)
    return tf.add(z , 10)

result = compute_graph(tf.constant(5) , tf.constant(3))
print("Graph Result:",result)

# Display the computation graph
print("Graph Concrete Function:", compute_graph.get_concrete_function(tf.constant(5), tf.constant(3)))

print("\n=== Eager Execution Enabled ===")
print("Is Eager Execution Enabled?:", tf.executing_eagerly())

x = tf.Variable(5.0)
with tf.GradientTape() as tape:
    y = x**2 + 3*x + 2
dy_dx = tape.gradient(y, x)
print("Value of y:", y.numpy())
print("Gradient dy/dx:", dy_dx.numpy())

# Dynamic behavior example
for val in range(3):
    temp = tf.constant(val)
    print(f"Square of {val}:", tf.square(temp).numpy())

=== Tensor Creation ===
Scalar: tf.Tensor(10, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Float Tensor: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Random Tensor:
 tf.Tensor(
[[-0.7983269  -0.8702872 ]
 [-0.49042052 -1.0878729 ]], shape=(2, 2), dtype=float32)
Zeros Tensor:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
Ones Tensor:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)

=== Tensor Manipulation ===
Reshaped Tensor:
 tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
First Row: tf.Tensor([0 1 2], shape=(3,), dtype=int32)
Element [1,2]: tf.Tensor(5, shape=(), dtype=int32)
Concatenated Tensor:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Addition: tf.Tensor([ 3  7 11], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([ 2 12 30], shape=(3,), dtype=int32)
Matrix Multiplication:
 tf.Tensor([[11]], shape=(1